name: Deploy CDK

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout code

env:
  AWS_REGION: us-east-1
  NODE_OPTIONS: "--no-warnings"  # Suppresses Node.js warnings

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # LTS version 20
          cache: 'npm'       # Enable caching for faster installs

      - name: Install dependencies
        run: npm ci          # Clean install using package-lock.json

      - name: Run tests
        run: npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::314146335501:role/cdk-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-CDK-Deploy
          role-duration-seconds: 3600

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Verify CDK environment
        run: |
          # Check if the environment is bootstrapped
          if ! aws cloudformation describe-stacks --stack-name CDKToolkit --region $AWS_REGION >/dev/null 2>&1; then
            echo "::error::CDK environment is not bootstrapped in region $AWS_REGION"
            exit 1
          fi
          echo "CDK environment is properly bootstrapped"

      - name: CDK Synth
        run: npx cdk synth

      - name: CDK Diff
        run: npx cdk diff

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never --verbose
