name: Deploy CDK

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  NODE_OPTIONS: "--no-warnings"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::314146335501:role/cdk-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-CDK-Deploy
          role-duration-seconds: 3600
          audience: sts.amazonaws.com

      - name: Force CDK Bootstrap
        run: |
          aws cloudformation delete-stack \
            --stack-name CDKToolkit \
            --region ${{ env.AWS_REGION }} || true
          
          aws cloudformation wait stack-delete-complete \
            --stack-name CDKToolkit \
            --region ${{ env.AWS_REGION }} || true

          npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }} \
            --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
            --trust ${{ secrets.AWS_ACCOUNT_ID }} \
            --force

      - name: Verify Bootstrap
        run: |
          aws s3 ls | grep cdk-hnb659fds-assets || exit 1
          aws cloudformation describe-stacks \
            --stack-name CDKToolkit \
            --region ${{ env.AWS_REGION }} || exit 1

      - name: Ensure GitHub OIDC Provider Exists
        run: |
          set -e
          EXISTING=$(aws iam list-open-id-connect-providers --query "OpenIDConnectProviderList[*].Arn" --output text)
          if [[ "$EXISTING" != *"token.actions.githubusercontent.com"* ]]; then
            echo "Creating GitHub OIDC Provider..."
            aws iam create-open-id-connect-provider \
              --url https://token.actions.githubusercontent.com \
              --client-id-list sts.amazonaws.com \
              --thumbprint-list 6938fd4d98bab03faadb97b34396831e3780aea1
          else
            echo "GitHub OIDC provider already exists. Skipping creation."
          fi

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never --verbose
