name: Deploy CDK

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout code

env:
  AWS_REGION: us-east-1
  NODE_OPTIONS: "--no-warnings"  # Suppresses Node.js warnings

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # LTS version 20
          # Cache parameter removed here

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Generating package-lock.json..."
            npm install --package-lock-only
          else
            echo "package-lock.json already exists"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::314146335501:role/cdk-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-CDK-Deploy
          role-duration-seconds: 3600

      - name: CDK Bootstrap (if needed)
        run: npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}

      - name: CDK Diff
        run: npx cdk diff

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never --verbose
